replicaCount: 2

env:
  plugins: "bundled,opa"

proxy:
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 80

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001

ingressController:
  enabled: true
